#!/bin/sh

set -e
set -x

csr () {

    CSR=$2/$3.csr
    CSR_NAME=$4-csr
    openssl req -new -config $1 -out $CSR -keyout $2/$3.key

    cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: $CSR_NAME
spec:
  groups:
  - system:authenticated
  request: $(cat $CSR | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
    kubectl certificate approve $CSR_NAME
    kubectl get csr $CSR_NAME -o jsonpath='{.status.certificate}' | base64 -d > $2/$3.crt
    kubectl create secret generic $4 --from-file $2
}

if [ ! -d ssl ]; then
    mkdir ssl
fi

rm -rf ssl/dockerwatch/
mkdir ssl/dockerwatch/

# csr dockerwatch-openssl.conf ssl/dockerwatch server dockerwatch-server

csr dockerwatch-dist-openssl.conf ssl/dockerwatch dist dockerwatch-dist

rm -rf ssl/dockerwatch_mnesia/
mkdir ssl/dockerwatch_mnesia/
csr dockerwatch-mnesia-dist-openssl.conf ssl/dockerwatch_mnesia dist dockerwatch-mnesia-dist

