apiVersion: v1
kind: Service
metadata:
  name: dockerwatch
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 8443
    protocol: TCP
    name: https
  selector:
    name: dockerwatch
  type: NodePort
