apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: dockerwatch-mnesia
  name: dockerwatch-mnesia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dockerwatch-mnesia
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: dockerwatch-mnesia
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      containers:
      - image: sekidocker.rnd.ki.sw.ericsson.se/proj-erlang/dockerwatch-mnesia
        name: dockerwatch-mnesia
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
        stdin: true
        tty: true
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
        - name: seki
---
apiVersion: v1
kind: Service
metadata:
  name: dockerwatch-mnesia
spec:
  ports:
  - port: 12345
    protocol: TCP
  selector:
    name: dockerwatch-mnesia
