apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mnesia
  name: mnesia
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mnesia
  strategy:
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mnesia
    spec:
      containers:
      - image: sekidocker.rnd.ki.sw.ericsson.se/proj-erlang/dockerwatch-mnesia
        name: mnesia
        command:
        - erl
        args:
        - -sname mnesia
        - -s mnesia
        - -start_epmd false
        - -epmd_module epmd_static
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
          protocol: TCP
        stdin: true
        tty: true
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
