apiVersion: v1
kind: Service
metadata:
  name: dockerwatch
  labels:
    app: dockerwatch
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  selector:
    app: dockerwatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  ## Name and labels of the Deployment
  labels:
    app: dockerwatch
  name: dockerwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerwatch
  template:
    metadata:
      labels:
        app: dockerwatch
    spec:
      containers:
      ## The container to launch
      - image: dockerwatch
        name: dockerwatch
        imagePullPolicy: Never ## Set to Never as we built the image in the cluster
        stdin: true
        tty: true
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
            - name: kube-keypair
              readOnly: true
              mountPath: /etc/ssl/certs
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BACKEND
          value: mnesia.default.svc.cluster.local
        - name: PORT
          value: "12345"
      volumes:
        - name: kube-keypair
          secret:
            secretName: dockerwatch
