apiVersion: v1
kind: Service
metadata:
  name: dockerwatch
  labels:
    app: dockerwatch
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  selector:
    app: dockerwatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  ## Name and labels of the Deployment
  labels:
    app: dockerwatch
  name: dockerwatch
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dockerwatch  # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: dockerwatch # has to match .spec.selector.matchLabels
    spec:
      containers:
      ## The container to launch
      - name: dockerwatch
        image: dockerwatch
        imagePullPolicy: Never ## Set to Never as we built the image in the cluster
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
            - name: kube-keypair
              readOnly: true
              mountPath: /etc/ssl/certs
        env:
        - name: BACKEND
          value: db.default.svc.cluster.local
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command:
              - dockerwatch/bin/dockerwatch
              - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: kube-keypair
          secret:
            secretName: dockerwatch
